<?php

require_once __DIR__ . '/alg_block.interface.inc';

/**
 * Implementation of hook_menu().
 *
 * @return An array of menu items.
 */
function alg_block_menu() {
  $items = array();

  $items['page/1'] = array(
    'page callback' => '_alg_block_page_1',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * function callback for page 1
 *
 * @return boolean
 */
function _alg_block_page_1() {
  return 'Page N°1';
}

function alg_block_call_router($op = 'list', $delta = 0, $edit = array()) {
  require_once drupal_get_path('module', 'alg_block') . '/alg_block.router.inc';
  $router = alg_block_router::getInstance();

  switch ($op) {
    case 'list':
      return $router->listBlock();
      break;
    case 'configure':
      return $router->configureBlock($delta);
      break;
    case 'save':
      return $router->saveBlock($delta, $edit);
      break;
    case 'view':
      return $router->viewBlock($delta);
      break;
    default:
      break;
  }
}

/**
 * Implementation of hook_block().
 *
 * @param $op What kind of information to retrieve about the block.
 * Possible values: list, configure, save, view.
 * @param $delta Which block to return.
 * @param $edit Data from a configuration form, if submitted.
 */
function alg_block_block($op = 'list', $delta = 0, $edit = array()) {
  return alg_block_call_router($op, $delta, $edit);
}
