<?php

/**
 * @file
 * This is an handler of block for d6
 */

/**
 * Implements of hook_init().
 */
function alg_block_init() {
  module_load_include('router.inc', 'alg_block');
  module_load_include('interface.inc', 'alg_block');
}

/**
 * Implements hook_block().
 *
 * @param string $op
 *   What kind of information to retrieve about the block.
 *   Possible values: list, configure, save, view.
 * @param string $delta
 *   Which block to return.
 * @param array $edit
 *   Data from a configuration form, if submitted.
 */
function alg_block_block($op = 'list', $delta = 0, $edit = array()) {
  // Get router instance.
  $router = AlgBlockRouter::getInstance();

  switch ($op) {
    case 'list':
      return $router->listBlock();
      break;
    case 'view':
      return $router->viewBlock($delta);
      break;
  }
}
